[tool.black]
line-length = 119

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "aioimaplib",
  "strictyaml",
]
strict = true
warn_return_any = false
